[font]
size = 11.5

[font.glyph_offset]
x = 0
y = 0 

[font.offset]
x = 0
y = 0 

[font.bold]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
import = [
  # "~/.config/alacritty/gruvbox-material.toml",
  # "~/.config/alacritty/gruvbox-material-hard-dark.toml",
  # "~/.config/alacritty/tokyonight-day.toml",
  "~/.config/alacritty/tokyonight-moon.toml",
  # "~/.config/alacritty/gruvbox-material-hard-light.toml",
  # "~/.config/alacritty/gruvbox-hard-dark.toml",
  # "~/.config/alacritty/gruvbox-hard-light.toml",
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/github-light-tritanopia.toml"
]

